Adds kubernetes audit logs config
UKHomeOffice/docker-logstash-kubernetes pull request #36
Opened 2017-01-20 17:04 UTC by marcinc

2017-01-20 17:09 UTC, vaijab requested changes

2017-01-20 17:09 UTC, vaijab commented on conf.d/20_output_kubernetes_audit.conf
> +    # Extract timestamp of the acutal event and overwrite @timestamp
`acutal` typo.

2017-01-20 17:09 UTC, vaijab commented on conf.d/20_output_kubernetes_audit.conf
> +      split => {
Maybe add a comment why you're splitting here?

2017-01-20 17:09 UTC, vaijab commented on conf.d/20_output_kubernetes_audit.conf
> +filter {
Should probably add `elasticsearch` to the file name.

2017-01-20 20:35 UTC, vaijab requested changes
If you could address one comment, otherwise looks good. Thanks!

2017-01-20 20:35 UTC, vaijab commented on conf.d/20_output_kubernetes_audit_elasticsearch.conf
> +      index => "kubernetes-audit-%ELASTICSEARCH_INDEX_SUFFIX%%{+YYYY.MM.dd}"
Should probably push to `kubernetes-` index and set document_type to `audit`.

2017-01-23 10:40 UTC, marcinc commented on conf.d/20_output_kubernetes_audit_elasticsearch.conf
> +      index => "kubernetes-audit-%ELASTICSEARCH_INDEX_SUFFIX%%{+YYYY.MM.dd}"
Sure. Thought we wanted to separate that entirely but yeah... makes sense.

2017-01-23 10:42 UTC, vaijab approved these changes
LGTM

2017-01-23 10:57 UTC, merged